name: Keep Alive
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > keepalive.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add keepalive.txt
          git commit -m "Auto commit to keep actions alive" || exit 0
          git push
